[build]
builder = "nixpacks"

[deploy]
startCommand = "streamlit run app.py --server.port=8000 --server.address=0.0.0.0 --server.headless=true"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10