services:
  # Staging Service
  - type: web
    name: loan-prediction-api-staging
    env: docker
    region: oregon
    plan: free
    branch: develop
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8501
      - key: ENVIRONMENT
        value: staging
    autoDeploy: true